export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Adicionando o link da fonte no Head */}
        <link
          href="https://fonts.googleapis.com/css2?family=Alexandria:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ fontFamily: "Alexandria, sans-serif", margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
